### ISSUE TITLE
Apps get backed up again despite not being used in the interim

### ISSUE THREAD

**Issue by VictorVow** [stevesoltys/backup#634] opened 2024-03-13 07:19 UTC
Every day I get many of the same apps being backed up again despite having not been used that day. This means a lot of extra data that I have to sync for no reason when the previous backup for these apps was exactly the same.

**Comment by grote** [comment] 2024-03-13 12:19
unfortunately, that's how the Android backup API works. We could try to add deduplication here and only upload what's new, but that brings other challenges as we only get app data in small byte chunks from the API.

This ticket is related to or even a duplicate of #566

**Comment by VictorVow** [comment] 2024-03-13 12:39
Ah I see, I couldn't find an old issue with the same keywords. Yeah deduplication makes sense as a fix - running that and deleting the new, unchanged backup would work here to prevent an unnecessary extra upload.

**Closed as completed** 2024-03-13 12:41 UTC
Labels: duplicate
