### ISSUE TITLE
Nextcloud only usable if NOT protected by app passcode

### ISSUE THREAD

**Issue by ASerbinski** [stevesoltys/backup#350] opened 2021-12-22 16:48 UTC
This is obviously due to the use of SAF as a means of interacting with Nextcloud, since Nextcloud doesn't enable SAF unless it is unprotected. A secondary problem caused by the use of SAF is that it won't work unless the Nextcloud application is actually installed and configured, which may not be an option during system setup.

I would suggest that a better way to interact with Nextcloud would be through its API/WebDAV. This would both allow Nextcloud to be protected by app passcode, and would make it possible to restore from Nextcloud during system setup and before Nextcloud can be installed on the device.

**Comment by grote** [comment] 2022-04-26 14:24
Duplicate of #317

**Closed as completed by grote** 2022-04-26 14:24 UTC
Labels: duplicate
