### ISSUE TITLE
No apparent way to restore single apps

### ISSUE THREAD

**Issue by chriswoope** [stevesoltys/backup#398] opened 2022-04-23 22:31 UTC
It seems the restore functionality is incredibly lacking, apparently only supporting restoring the whole backup.

Obviously restoring single apps is crucial functionality since it allows to recover from accidental changes to the app state (e.g. someone accidentally deletes a data item in the app).

Restoring the whole backup is clearly unsuitable since that will replace the data of all other apps, possibly resulting in old data being restored, or even catastrophic data loss in case the restore fails.

**Comment by grote** [comment] 2022-04-25 13:44
You can uninstall an app and then re-install it without Auto-Backup on. That will attempt to restore the app data from backup.

**Comment by grote** [comment] 2022-04-25 14:11
duplicate of #309

**Closed as completed by grote** 2022-04-25 14:11 UTC
Labels: duplicate

**Comment by chriswoope** [comment] 2022-04-25 21:20
The problem with that is that uninstalling deletes the app data, and if the backup restoration fails upon the new install (e.g. the backup got corrupted somehow), then app data will be completely lost instead of partially lost.

So it seems like a more reliable mechanism and easy-to-use mechanism is needed.

**Comment by grote** [comment] 2022-04-26 12:38
That is what  #309 is for.
