### ISSUE TITLE
Uninstalled apps should not be restored by default

### ISSUE THREAD

**Issue by lucasmz-dev** [stevesoltys/backup#800] opened 2024-11-17 18:14 UTC
SeedVault keeps data from apps that were not present at the time of the last backup, that's all fine, the user may not want that data to be lost and it can end up being helpful. What I don't find great is that when restoring, all these uninstalled apps will be marked for restoring, since these were not present last backup, it'd be better to keep them as an option, but the restore process should not mark them automatically to be restored, the user *can* go and unselect these, but it's inconvenient and unclear.

**Comment by grote** [comment] 2024-11-18 13:35
> What I don't find great is that when restoring, all these uninstalled apps will be marked for restoring

Are you sure about this? Can you confirm with the latest version which should be available with CalyxOS 5?

Otherwise dupe of https://github.com/seedvault-app/seedvault/issues/299

**Comment by lucasmz-dev** [comment] 2024-11-19 12:50
Yeah @grote 
![Screenshot_20241119-094940](https://github.com/user-attachments/assets/928d38ff-f793-4ad2-8d6d-08c2393f6b76)

**Comment by grote** [comment] 2024-11-19 14:17
And this backup made 9hrs ago was made with CalyxOS 6.1.0?

@t-m-w did you ever test how v2 backup behaves with uninstalled apps?

**Comment by lucasmz-dev** [comment] 2024-11-19 15:24
This isn't backup v2, I don't have a Pixel so I'm using 5.13.0 :D

**Comment by t-m-w** [comment] 2024-11-19 15:52
> And this backup made 9hrs ago was made with CalyxOS 6.1.0?
> 
> @t-m-w did you ever test how v2 backup behaves with uninstalled apps?

I don't know if I specifically tried it, but on trying it just now, it behaves as expected; uninstall app, take backup, try restore, and the app is not in the list of apps to restore. (I didn't fully proceed with an actual restore because this was on my daily driver.)

> This isn't backup v2, I don't have a Pixel so I'm using 5.13.0 :D

That'll do it, probably. :( Hopefully 6.x will be ready for other devices soon!

**Comment by grote** [comment] 2024-11-19 16:16
ok, thanks for checking. so as expected a duplicate of https://github.com/seedvault-app/seedvault/issues/299

**Closed as completed by grote** 2024-11-19 16:16 UTC
Labels: needs info
