### ISSUE TITLE
"Backup now" button is disabled

### ISSUE THREAD

**Issue by rugk** [stevesoltys/backup#460] opened 2022-10-15 11:40 UTC
## STR

I just used it normally and the "backup now" button is greyed out. I have no idea why, though.
Also the regular/automatic backups seems to work, I just cannot trigger it manually.

### Screenshot

![Screenshot_20221015-133344](https://user-images.githubusercontent.com/11966684/195984482-cd7a18d8-fc22-4912-8d78-246b336e84fb.png)

The device has no SIM yet, maybe that's a problem? But that really should not be a problem, after all… :upside_down_face: 
**Edit:** No, after putting in a SIM the same thing remains.

## system 

Device: Fairphone 4 (FP4)  
OS: Android 13, CalyxOS 4.2.2  
source: F-Droid  
version: v. 13-3.1
Build-ID: `TP1A.221005.003.22402020`

**Comment by grote** [comment] 2022-10-18 12:57
duplicate of #457

**Closed as completed by grote** 2022-10-18 12:57 UTC
Labels: duplicate
