### ISSUE TITLE
com.qualcomm.qti.telephonyservice fails entire backup: Error -1003

### ISSUE THREAD

**Issue by old-lateral** [stevesoltys/backup#530] opened 2023-04-01 14:51 UTC
Have tried running the backup multiple times on my Sony Xperia 5 II (pdx206) with LineageOS 20.0 (Android 13) installed. Backup fails around 89% regardless of backup target. Tried internal storage and a mcroSD card. Sufficient storage space on both. Seedvault version 13-3.3

Have tries with "Aromatic Restore" option enabled and disabled, as well as (Unlimited app quota) in "Expert Settings" enabled and disabled. Backup fails in each case.

App Log attached
[seedvault-13-3.3-1680359518592.txt](https://github.com/seedvault-app/seedvault/files/11129815/seedvault-13-3.3-1680359518592.txt)

**Comment by grote** [comment] 2023-04-04 12:57
possible cause:

```ruby
04-01 10:00:17.904  1692 16430 I PFTBT   : Initiating full-data transport backup of com.qualcomm.qti.telephonyservice token: 632676094
04-01 10:00:17.909  1692 20363 D BackupManagerService: [UserID:0] awaiting agent for ApplicationInfo{d6c6829 com.qualcomm.qti.telephonyservice}
04-01 10:00:17.924  1692  2827 I ActivityManager: Process com.qti.phone (pid 20319) has died: pers PER 
04-01 10:00:17.925  1692  2827 W ActivityManager: Scheduling restart of crashed service com.qualcomm.qti.telephonyservice/.QtiTelephonyService in 0ms for persistent
04-01 10:00:17.925  1692  2827 W ActivityManager: Scheduling restart of crashed service com.qualcomm.qcrilmsgtunnel/.QcrilMsgTunnelService in 0ms for persistent
04-01 10:00:17.925  1692  2827 W ActivityManager: Scheduling restart of crashed service com.qti.phone/.ExtTelephonyService in 0ms for persistent
04-01 10:00:17.926  1692  2827 W ActivityManager: Re-adding persistent process ProcessRecord{ce35a5f 20319:com.qti.phone/u0a132}
04-01 10:00:17.930  1692  1729 W BackupManagerService: agentDisconnected: the backup agent for com.qualcomm.qti.telephonyservice died: cancel current operations
04-01 10:00:17.930  1692 20363 I BackupManagerService: [UserID:0] got agent null
04-01 10:00:17.930  1692 20363 W BackupManagerService: Unable to bind to full agent for com.qualcomm.qti.telephonyservice
04-01 10:00:17.930  1692 20364 V LifecycleOperationStorage: [UserID:0] Cancel: token=7fdd6aff
04-01 10:00:17.930  1692 20364 W PFTBT   : Full backup cancel of com.qualcomm.qti.telephonyservice
04-01 10:00:17.930  1692 20364 W ActivityManager: Unbinding backup agent with no active backup
04-01 10:00:17.930  1692 20364 W ActivityManager: Process/uid not found attempting kill of com.qti.phone / 10132
04-01 10:00:17.933  1692 20364 V LifecycleOperationStorage: [UserID:0] Cancel: token=25b5defe
04-01 10:00:17.940  1692  1730 I ActivityManager: Start proc 20367:com.qti.phone/u0a132 for restart com.qti.phone
04-01 10:00:19.304  1692 16430 W PFTBT   : Error -1003 backing up com.qualcomm.qti.telephonyservice
04-01 10:00:19.304  1692 16430 I PFTBT   : Transport suggested backoff=0
04-01 10:00:19.304  1692 16430 W PFTBT   : Application failure for package: com.qualcomm.qti.telephonyservice
04-01 10:00:19.304  1692 16430 W ActivityManager: Unbinding backup agent with no active backup
04-01 10:00:19.305  1692 16430 I PFTBT   : Unbinding agent in com.qualcomm.qti.telephonyservice
04-01 10:00:19.306  1692 16430 W ActivityManager: Unbinding backup agent with no active backup
04-01 10:00:19.307  1692 16430 I PFTBT   : Initiating full-data transport backup of com.qualcomm.timeservice token: 632676094
04-01 10:00:19.307  1692 16430 I PFTBT   : Full backup completed with status: -2003
04-01 10:00:19.314  1692 16430 I PFTBT   : Full data backup pass finished.
04-01 10:00:19.315  1692 16430 V BackupManagerService: [UserID:0] Released wakelock:*backup*-0-3669
```

**Comment by grote** [comment] 2023-04-04 12:59
Related to or duplicate of #485.

**Comment by old-lateral** [comment] 2023-04-07 19:14
> possible cause:
> 
> ```ruby
> 04-01 10:00:17.904  1692 16430 I PFTBT   : Initiating full-data transport backup of com.qualcomm.qti.telephonyservice token: 632676094
> 04-01 10:00:17.909  1692 20363 D BackupManagerService: [UserID:0] awaiting agent for ApplicationInfo{d6c6829 com.qualcomm.qti.telephonyservice}
> 04-01 10:00:17.924  1692  2827 I ActivityManager: Process com.qti.phone (pid 20319) has died: pers PER 
> 04-01 10:00:17.925  1692  2827 W ActivityManager: Scheduling restart of crashed service com.qualcomm.qti.telephonyservice/.QtiTelephonyService in 0ms for persistent
> 04-01 10:00:17.925  1692  2827 W ActivityManager: Scheduling restart of crashed service com.qualcomm.qcrilmsgtunnel/.QcrilMsgTunnelService in 0ms for persistent
> 04-01 10:00:17.925  1692  2827 W ActivityManager: Scheduling restart of crashed service com.qti.phone/.ExtTelephonyService in 0ms for persistent
> 04-01 10:00:17.926  1692  2827 W ActivityManager: Re-adding persistent process ProcessRecord{ce35a5f 20319:com.qti.phone/u0a132}
> 04-01 10:00:17.930  1692  1729 W BackupManagerService: agentDisconnected: the backup agent for com.qualcomm.qti.telephonyservice died: cancel current operations
> 04-01 10:00:17.930  1692 20363 I BackupManagerService: [UserID:0] got agent null
> 04-01 10:00:17.930  1692 20363 W BackupManagerService: Unable to bind to full agent for com.qualcomm.qti.telephonyservice
> 04-01 10:00:17.930  1692 20364 V LifecycleOperationStorage: [UserID:0] Cancel: token=7fdd6aff
> 04-01 10:00:17.930  1692 20364 W PFTBT   : Full backup cancel of com.qualcomm.qti.telephonyservice
> 04-01 10:00:17.930  1692 20364 W ActivityManager: Unbinding backup agent with no active backup
> 04-01 10:00:17.930  1692 20364 W ActivityManager: Process/uid not found attempting kill of com.qti.phone / 10132
> 04-01 10:00:17.933  1692 20364 V LifecycleOperationStorage: [UserID:0] Cancel: token=25b5defe
> 04-01 10:00:17.940  1692  1730 I ActivityManager: Start proc 20367:com.qti.phone/u0a132 for restart com.qti.phone
> 04-01 10:00:19.304  1692 16430 W PFTBT   : Error -1003 backing up com.qualcomm.qti.telephonyservice
> 04-01 10:00:19.304  1692 16430 I PFTBT   : Transport suggested backoff=0
> 04-01 10:00:19.304  1692 16430 W PFTBT   : Application failure for package: com.qualcomm.qti.telephonyservice
> 04-01 10:00:19.304  1692 16430 W ActivityManager: Unbinding backup agent with no active backup
> 04-01 10:00:19.305  1692 16430 I PFTBT   : Unbinding agent in com.qualcomm.qti.telephonyservice
> 04-01 10:00:19.306  1692 16430 W ActivityManager: Unbinding backup agent with no active backup
> 04-01 10:00:19.307  1692 16430 I PFTBT   : Initiating full-data transport backup of com.qualcomm.timeservice token: 632676094
> 04-01 10:00:19.307  1692 16430 I PFTBT   : Full backup completed with status: -2003
> 04-01 10:00:19.314  1692 16430 I PFTBT   : Full data backup pass finished.
> 04-01 10:00:19.315  1692 16430 V BackupManagerService: [UserID:0] Released wakelock:*backup*-0-3669
> ```

Update, the error pops up only when the backup is triggered manually. Seedvault still continues in background and no error pops up during regular scheduled backups. "Backup Status" will show "Last Backup: 15 minutes ago" or whatever given time from last backup with no issues.

Restoring a backup on a Motorola G7 Plus restored apps, most app data, call logs and text messages without issue, so the backup seems to be running successfully as a background  process but shows a fail error when triggered manually.

**Comment by baschi29** [comment] 2024-02-19 18:03
The issue is still present with Lineage OS 21 (Android 14) and seedvault 14-4.0

**Comment by grote** [comment] 2024-03-14 13:44
Closing as duplicate of https://github.com/seedvault-app/seedvault/issues/491

**Closed as not planned by grote** 2024-03-14 13:44 UTC
