### ISSUE TITLE
AssertionError: Error reading metadata from cache

### ISSUE THREAD

**Issue by rugk** [stevesoltys/backup#449] opened 2022-09-17 10:50 UTC
Shown twice:

```
FATAL EXCEPTION: main
Process: com.stevesoltys.seedvault, PID: 19041
java.lang.AssertionError: Error reading metadata from cache
	at com.stevesoltys.seedvault.metadata.MetadataManager.getMetadata(MetadataManager.kt:48)
	at com.stevesoltys.seedvault.metadata.MetadataManager.getBackupToken(MetadataManager.kt:209)
	at com.stevesoltys.seedvault.App.migrateTokenFromMetadataToSettingsManager(App.kt:113)
	at com.stevesoltys.seedvault.App.access$migrateTokenFromMetadataToSettingsManager(App.kt:44)
	at com.stevesoltys.seedvault.App$onCreate$1.invoke(App.kt:80)
	at com.stevesoltys.seedvault.App$onCreate$1.invoke(App.kt:79)
	at com.stevesoltys.seedvault.AppKt.permitDiskReads(App.kt:142)
	at com.stevesoltys.seedvault.App.onCreate(App.kt:79)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1227)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6762)
	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.io.IOException
	at com.stevesoltys.seedvault.metadata.MetadataManager.getMetadata(MetadataManager.kt:45)
	... 18 more
```

Catched by Scoop.

Happened likely during backup.

## system

Device: Pixel 4 (flame)  
OS: Android 12, CalyxOS 3.9.0. 
source: F-Droid  
version: v 12-3.0
Build-ID: `SQ3A.220705.003.A1.22309000`  

## question

I now have two devices backing up into nextcloud with the same passphrase.
Given when restoring i can select what backup to restore I would have guessed that this is fine, is not it?

Or is this actually not supported and causes this error?

**edit:** that exception also happenswhen trying to open seedvault e.g. from the settings.

**Comment by grote** [comment] 2022-09-19 14:03
How much free space is there on the internal storage of the device?

**Comment by rugk** [comment] 2022-10-15 11:32
Not a lot, that device is constantly being full and I need to delete stuff… :upside_down_face: 
(Maybe a better error would be needed though?)

But is it generally fine to use the same storage for two devices? (with the same passphrase)

**Comment by grote** [comment] 2022-10-18 12:55
Then this is a duplicate of https://github.com/seedvault-app/seedvault/issues/213

> But is it generally fine to use the same storage for two devices? (with the same passphrase)

On recent versions of Seedvault, yes.

**Closed as completed by grote** 2022-10-18 12:55 UTC
Labels: duplicate
