### ISSUE TITLE
[Bug Report] Can't restore backup correct work profile when shelter recreates the profile

### ISSUE THREAD

**Issue by Nonie689** [stevesoltys/backup#501] opened 2023-01-12 09:48 UTC
Dear Dev-Team,

I can't restore backup correct work profile when shelter recreates the work profile.

I can't select the correct backup... maybe it has a new random ID...

hope you will fix this issue...!

**Comment by grote** [comment] 2024-05-31 17:49
sounds like a duplicate of https://github.com/seedvault-app/seedvault/issues/571

**Closed as completed by grote** 2024-05-31 17:49 UTC
