### ISSUE TITLE
Allow to set manual schedule

### ISSUE THREAD

**Issue by mozzieongit** [stevesoltys/backup#429] opened 2022-07-28 19:43 UTC
Seedvault often starts a backup a few minutes before I leave my home. That means that the backup will be uploaded via mobile data instead of Wi-Fi. And as I don't have such a large data volume, this is a problem.

My current solution is killing both apps (seedvault and nextcloud) and manually starting another backup when home, but that is a suboptimal and annoying solution.

Wished for solution: add manual backup schedules

**Comment by grote** [comment] 2022-08-15 20:26
See https://github.com/seedvault-app/seedvault/issues/431#issuecomment-1215751245

Title is duplicate of #316

**Closed as completed** 2022-08-15 20:26 UTC
Labels: duplicate
