### ISSUE TITLE
Backup always fails (Internal storage)

### ISSUE THREAD

**Issue by utmost-premise** [stevesoltys/backup#638] opened 2024-03-29 21:13 UTC
## Device info

- Device: Xiaomi Poco F5
- Codename: marble
- Model: 23049PCD8G

## System info

- Seedvault Version: `14-4.0`
- No GApps installed
- Custom ROM thread: <https://xdaforums.com/t/rom-14-unofficial-lineageos-21-for-xiaomi-poco-f5-redmi-note-12-turbo.4655286/>
- Android version: `14`
- LineageOS version: `21-20240306-UNOFFICIAL-marble`
- Android Security Update: `2024-02-05`
- Vendor security patch level: `2024-01-01`
- Kernel version: `5.10.205-gki-g6d95079b4ceb #1 Wed Mar 6 22:02:58 UTC 2024`
- Build date: `Wed Mar  6 21:56:35 UTC 2024`
- Build number: `lineage_marble-userdebug 14 UQ1A.240205.004 eng.jens.20240306.215854`

### Magisk

- Installed version: 27.0
- Zygisk enabled
- Enforce DenyList disabled

#### Enabled modules

- Systemless Hosts
- [microG Installer Revived](https://github.com/nift4/microg_installer_revived)
- [Zygisk - LSPosed v1.9.2](https://github.com/LSPosed/LSPosed)
    - Enabled module: [FakeGapps (Signature spoofing)](https://github.com/whew-inc/FakeGApps)

## Issue

Backing up always fails with notification "Backup failed", no additional info.

- Backup location set to Device (Internal storage).
- Storage backup (experimental) > Backup my files: disabled
  
Tried different options:

1. App backup enabled, unlimited app quota and D2D backups disabled
2. App backup enabled, unlimited app quota disabled, and D2D backups enabled
3. App backup enabled, unlimited app quota enabled, and D2D backups disabled
4. App backup disabled, unlimited app quota enabled, and D2D backups disabled

Even tried removing **.SeedVaultAndroidBackup** folder, force stopping and clearing SeedVault's data, and setting it up again, but to no avail.

Also tried disabling all Magisk modules, LSPosed and Zygisk, backup still failing.

Even though backup fails, **.SeedVaultAndroidBackup** folder contains 3.34 GB of data.

Logcat (exported from Seedvault) attached.

Edit: log removed just for extra precaution since the culprit was found. I can send it again if needed.

**Comment by chirayudesai** [comment] 2024-03-29 22:02
`W PFTBT   : Error -1003 backing up com.qualcomm.qcrilmsgtunnel`

Should be fixed by #635

**Comment by grote** [comment] 2024-04-01 11:56
duplicate of #491

**Closed as not planned by grote** 2024-04-01 11:56 UTC
Labels: duplicate
