### ISSUE TITLE
Partial restore of backup

### ISSUE THREAD

**Issue by ligix** [stevesoltys/backup#661] opened 2024-05-18 09:30 UTC
Currently there is no way to do a partial restore, you can either restore everything or restore nothing.

This isn't really a major issue until system apps come into play which, if backed up, can corrupt the already installed one (like the contacts and the dialer app, if you take a backup on lineageos and then restore it to graphene it makes the dialer crash and the contacts app doesn't actually get restored).

It'd be nice if you could pick which applications, which data and which files to restore.

**Comment by grote** [comment] 2024-05-20 12:51
duplicate of https://github.com/seedvault-app/seedvault/issues/309

**Closed as completed by grote** 2024-05-20 12:51 UTC
