### ISSUE TITLE
Auto-delete older backups

### ISSUE THREAD

**Issue by aj9669** [stevesoltys/backup#745] opened 2024-09-13 12:06 UTC
When backing up to my Nextcloud, whether it's over DAV or via Nextcloud, it accumulates all backups and causes my storage to fill up, until I have none left. Is there no possibility to automatically delete all old backups? 

I use CalyxOS (always the newest stable version) on a Fairphone 4.

**Comment by grote** [comment] 2024-09-13 12:59
kind of a duplicate of https://github.com/seedvault-app/seedvault/issues/559

I suggest using the integrated WebDAV backend instead for now. Backups currently get duplicated only for fatal backup errors, will be fixed in an upcoming verison.

**Comment by grote** [comment] 2024-10-14 12:38
With #750 merged, we new only keep 3 daily snapshots and 2 weekly ones (one from this and one from last week). Anything older than this gets cleaned up automatically after each backup run.

**Closed as completed by grote** 2024-10-14 12:38 UTC
