### ISSUE TITLE
Running apps restart when backup finishes

### ISSUE THREAD

**Issue by eternal-sorrow** [stevesoltys/backup#791] opened 2024-11-08 14:25 UTC
I've setup the backup to run on a schedule. If I use the phone when it runs backup, apps that are running currently get restarted when the backup finishes. As if the app was killed and instantly started anew from the launcher. I lose whatever I was doing in the app in that moment.

**Comment by grote** [comment] 2024-11-08 16:12
I think this is a duplicate of https://github.com/seedvault-app/seedvault/issues/778

**Closed as completed by grote** 2024-11-08 16:12 UTC
Labels: duplicate
