### ISSUE TITLE
Seedvault Failing to back up to Nextcloud and USB

### ISSUE THREAD

**Issue by Lonestarag** [stevesoltys/backup#463] opened 2022-11-04 13:44 UTC
I'm on a Pixel 6 Pro running GrapheneOS. I'm trying to run a backup and it fails when I try and backup to Nextcloud. I tried using a USB stick and it gets to 27% then fails. It does backup successfully to the phone. I'm assuming it might be a nextcloud issue but why wouldn't it back up to the USB? Thanks!

**Comment by grote** [comment] 2022-11-04 19:22
What Seedvault version are you on? Note https://github.com/seedvault-app/seedvault#requirements

Do you have logs from when it fails? Did you run some sort of fsck on the USB drive?

**Comment by Lonestarag** [comment] 2022-11-05 16:40
> What Seedvault version are you on? Note https://github.com/seedvault-app/seedvault#requirements
> 
> Do you have logs from when it fails? Did you run some sort of fsck on the USB drive?

I'm running 11-2.3. I didn't run anything on the USB drive. Does it need to be formatted in a certain filesystem? How do I take logs from when it fails? Thanks!

**Comment by jonmonty** [comment] 2022-11-06 16:40
Same exact issue here, Pixel 6 Pro running Graphene OS, Seedvault version 11-2.3, Nextcloud client app version 3.22.2. Seedvault fails to backup to Nextcloud and a USB drive freshly formatted using androids built in tools

**Comment by nickcalyx** [comment] 2022-11-06 16:49
@Lonestarag and @jonmonty  did you read the requirements note linked above ?  It could be an issue that your OS is using a several year old version of SeedVault, meant to be used with Android 11.  Maybe get them to update to a current version that is meant for Android 13 and then try again.

**Comment by Lonestarag** [comment] 2022-11-06 17:26
> @Lonestarag and @jonmonty did you read the requirements note linked above ? It could be an issue that your OS is using a several year old version of SeedVault, meant to be used with Android 11. Maybe get them to update to a current version that is meant for Android 13 and then try again.

I'm running the latest version of seedvault on grapheneos

**Comment by Lonestarag** [comment] 2022-11-06 23:31
> @Lonestarag and @jonmonty did you read the requirements note linked above ? It could be an issue that your OS is using a several year old version of SeedVault, meant to be used with Android 11. Maybe get them to update to a current version that is meant for Android 13 and then try again.

I gotcha.. thanks Nick. I'll see about them updating it.

**Comment by psic4t** [comment] 2022-11-16 14:07
Same here. Pixel 6 Pro, GrapheneOS, Seedvault 11-2-3.
No detailed error messages, only "Backup failed" at about 27%. Nextcloud uploads are ok.

**Comment by TobiGr** [comment] 2022-12-03 00:31
Using Seedvault 11-2.3 on Android 11. I also get the omnious "Backup failed" toast at the end of the backup phase. Additionally, it says "0 of 
32 apps backed up. Tap to learn more". That is odd, because  32 APK files are uploaded to my NextCloud, so I guess the error message is about the app data.
I tried to grab some lines via logcat which might be helpful. They mostly say 
- Error finding file blocking
- Error backing up content
- Error while writing APK or metadata for package.name

and are mostly caused by `FileNotFoundException` 

Apart from those, I've got a bunch of _StrictMode policy violation_ which I don't understand. I removed some info from the logs. You can download the logs [here](https://github.com/seedvault-app/seedvault/files/10145171/backup.log).

**Comment by Pilzinsel64** [comment] 2022-12-16 05:57
The same for me. Galaxy S10 with LineageOS 19.1, SeedVault 12-3.0
On October 23 it was the last successfull backup. Not possible since then. Also not possible to re-configure, will also fail to backup then at ~27% (not sure if exactly, but about this percentage number).
Nextcloud failes with for some files with `FileNotFoundException` exception mostly and that probably cause the failuar.

**Comment by Cmod777** [comment] 2022-12-22 21:35
versione 11-2.3

com.stevesoltys.seedvault
versionCode 30000231

targetSdk 33
minSdk 33

Cant backup on usb stick and dont understand why. The usb is new

**Comment by ernstlustig** [comment] 2022-12-29 21:26
ASUS Zenfone 8 with Lineage 19.1
Backup failed for Nextcloud. 
WebDAV appears to be a working alternative. (Use the WebDAV link bottom left in your settings and add in DAVx.)

**Comment by Cmod777** [comment] 2022-12-30 00:05
Maybe fixed with local backup > manual copy paste to Proton Drive folder

Folder was full, i will try again but no error displayed

**Comment by grote** [comment] 2023-01-02 14:13
@TobiGr thanks for the logs. There's lots of errors in there. Have you tried using the DavX5 app instead for accessing your nextcloud?

**Comment by TobiGr** [comment] 2023-01-02 16:24
I tried. I followed [this tutorial](https://gnulinux.ch/android-sicherung-mit-seedvault) to mount my NextCloud storage in Android. That worked and the storage is accessible via the default file manager. However, SeedVault does not recognize the WebDAV mount. It is not listed as backup location. I am using /e/ OS which comes with Android 11 (LOS) and SeedVault 11-2.3.

**Comment by trenfoight** [comment] 2023-01-06 21:25
> Maybe fixed with local backup > manual copy paste to Proton Drive folder
> 
> Folder was full, i will try again but no error displayed

Im dealing with a similiar issue...backup failing at around 29% for both usb and nextcloud using woelkli....i am able to backup locally and manually upload seed folder to nextcloud. When I do this, I do have the ability to see the restore files using the OS nextcloud backup process

**Comment by TheBrambleShark** [comment] 2023-01-08 05:31
Same issue here on Pixel 5 with Graphene OS and SeedVault 11-2.3.

For those facing this issue, if you can get backups to your internal storage to work, then you can sync your local backup with Nextcloud.

To set up the Nextcloud backup, go to the NextCloud app then open Settings > Auto Upload > Hamburger Button (three dots on top right) > Set Up a Custom Folder

Local Folder: Tap the dropdown at the top and choose 0 (or choose / then select Internal Storage), then select .SeedVaultAndroidBackup, then click Choose. This directory is located in the root of your local storage drive, so if my directions don't work for you, that's where you can find it. If you still don't see it, make sure a backup has run and make sure you have hidden files turned on.

Remote Folder: Hamburger button (top right), New Folder, type .SeedVaultAndroidBackup, click Create, then click Choose. You can adjust the remaining settings, but leave Use Subfolders unchecked.

After a few minutes, you should start seeing your backups appearing in your cloud directory in a way that best replicates selecting the Nexcloud source for backup. It's not ideal in that you are storing app data on your phone twice, but workarounds are never ideal. This should hopefully allow you to continue backing up your files until your OS developer can update SeedVault.

Amendment: Seems the root cause of this issue is in the NextCloud app (see below). The version of Seedvault in GrapheneOS needs updating as well, but it might not be a contributing factor for this specific issue.

**Comment by afflux** [comment] 2023-01-21 10:47
I see many FileNotFoundExceptions on .backup.metadata on my phone. Some debugging revealed this bug in the nextcloud app: https://github.com/nextcloud/android/issues/11283. I think this may be the same issue.

**Comment by 4parthy** [comment] 2023-02-27 14:41
Trying to backup to Nextcloud fails for me as well. 56% is the farthest I got so far. Here is a part of my logcat: https://pastebin.com/pGMrEYEx

**Comment by TheBrambleShark** [comment] 2023-02-28 00:43
GrapheneOS has updated SeedVault to 13-3.3. However, this issue persists on the new version.

Backing up to a my phone's hard drive and using Nextcloud to sync the folder as described in my last comment remains the only viable option.

**Comment by grote** [comment] 2023-05-31 16:23
This PR by @afflux should help with the Nextcloud issue: https://github.com/nextcloud/android/pull/11286

**Comment by taggart** [comment] 2023-08-10 17:49
I also wonder if there is an issue when switching the destination between nextcloud and usb. I had previously used nextcloud as destination, but was on a low bandwidth network and switched to usb in order to move data from and old phone to a new one. The backups sent to the usb drive were non-functional in the restore UI, it couldn't see them(see my comment in #462 ). Also at times when the backups to USB were running, I would see it sending things to nextcloud, like that had not been completely turned off.
The way I fixed it was clearing the seedvault data/cache on the phone I was backing up, used a clean usb drive, and then the resulting backup was functional. 
EDIT: I should note, I first setup seedvault to backup to nextcloud like a year ago, it's possible that some older version wound up doing something bad and maybe that's fixed, but the problem was only resolved by clearing the app data/cache and doing a fresh backup.

**Comment by afflux** [comment] 2023-09-21 20:35
> This PR by @afflux should help with the Nextcloud issue: [nextcloud/android#11286](https://github.com/nextcloud/android/pull/11286)

The Nextcloud android app v3.26 was recently released, with that fix included. The problem I found should be solved there.

**Closed as completed** 2024-09-24 17:34 UTC
Labels: needs info
