### ISSUE TITLE
Vanadium Config backup status is '!'

### ISSUE THREAD

**Issue by nandlab** [stevesoltys/backup#639] opened 2024-04-03 00:27 UTC
Vanadium is the modded Chromium browser in GrapheneOS. Vanadium Config backup status is a red '!' after a backup. I don't know, if it is the fault of Seedvault or Vanadium, but I wanted to report this.

**Comment by grote** [comment] 2024-09-24 16:56
thanks for the report, kinda a duplicate of https://github.com/seedvault-app/seedvault/issues/147

**Closed as completed by grote** 2024-09-24 16:56 UTC
