### ISSUE TITLE
No way to support multiple backups per location

### ISSUE THREAD

**Issue by chriswoope** [stevesoltys/backup#399] opened 2022-04-23 22:32 UTC
The location settings doesn't allow to specify a directory, which means that only one backup is allowed per location, and it's not possible to backup in an arbitrary folder.

This is basic functionality of any backup program that should be present in Seedvault since it's the only way to backup in several OSes.

It also means that it's not possible to switch backup locations to continue backing up the system while preserving an old backup that might have data that has since been deleted.

**Comment by grote** [comment] 2022-04-25 13:46
Duplicate of #340

**Closed as completed by grote** 2022-04-25 13:46 UTC
Labels: duplicate
