### ISSUE TITLE
Seedvault failing to back up on custom LineageOS 20.0 + microG ROM

### ISSUE THREAD

**Issue by nanoandrew4** [stevesoltys/backup#485] opened 2022-12-13 23:56 UTC
I'm using version 13-3.1 of the app, which is what the LineageOS build process includes in the ROM, and every time I try to back up locally, it gets to 82% and says the backup failed. Local contacts are waiting to be backed up, as well as some other apps. Here is a log of the process from when it starts to when it fails: 
[seedvault.log](https://github.com/seedvault-app/seedvault/files/10222990/seedvault.log)

If you need any more information I will be happy to provide it.

**Comment by grote** [comment] 2023-01-02 13:32
Relevant log:
```ruby
12-14 00:53:18.234  1733  1777 W BackupManagerService: agentDisconnected: the backup agent for com.qualcomm.qti.telephonyservice died: cancel current operations
12-14 00:53:18.234  1733  1777 W PFTBT   : Full backup cancel of com.qualcomm.qcrilmsgtunnel
12-14 00:53:18.234  1733  1777 W ActivityManager: Process/uid not found attempting kill of com.qti.phone / 10130
12-14 00:53:18.304 27844 27844 W com.qti.phone: ClassLoaderContext shared library size mismatch. Expected=0, found=2 (PCL[] | PCL[]{PCL[/system_ext/framework/qti-telephony-utils.jar*2060660896]#PCL[/system_ext/framework/qti-telephony-hidl-wrapper.jar*899869192]})
12-14 00:53:18.335   639   639 E SELinux : avc:  denied  { find } for pid=27844 uid=10130 name=vendor.qti.hardware.radio.qtiradio.IQtiRadioStable/slot1 scontext=u:r:vendor_qtelephony:s0:c130,c256,c512,c768 tcontext=u:object_r:default_android_service:s0 tclass=service_manager permissive=0
12-14 00:53:18.335 27844 27844 E QtiRadioFactory: Security exception while call into AIDL: java.lang.SecurityException: 
12-14 00:53:18.348 27844 27864 E QtiRadioProxy: CnE factory not supported: java.util.NoSuchElementException
12-14 00:53:18.348 27844 27864 E QtiRadioProxy: CnE IFactory.getService() returned null
12-14 00:53:18.348 27844 27864 E QtiRadioProxy: getDynamicSubscriptionManager() returned null
12-14 00:53:18.348 27844 27844 W ActivityThread: getPackageInfo() called with an older ApplicationInfo than the cached version for package com.qualcomm.qti.telephonyservice
12-14 00:53:18.438  1733 25804 W system_server: Long monitor contention with owner ActivityManager (1777) at void com.android.server.backup.fullbackup.PerformFullTransportBackupTask.handleCancel(boolean)(PerformFullTransportBackupTask.java:323) waiters=0 in void com.android.server.backup.fullbackup.PerformFullTransportBackupTask.run() for 204ms
12-14 00:53:18.439  1733 25804 W PFTBT   : Error -2003 backing up com.qualcomm.qcrilmsgtunnel
12-14 00:53:18.440  1733 25804 W PFTBT   : Backup cancelled. package=com.qualcomm.qcrilmsgtunnel, cancelAll=true
```

Maybe an upstream bug with that SELinux deny? They probably never tested backup.

@t-m-w can we consider this as a duplicate of #491 maybe?

**Comment by grote** [comment] 2023-04-10 17:56
https://github.com/seedvault-app/seedvault/issues/530#issuecomment-1500563751 suggests that this only affects manual backups. Maybe we include apps that the system knows to exclude on its own somehow?

**Comment by grote** [comment] 2024-03-14 13:44
Closing as duplicate of https://github.com/seedvault-app/seedvault/issues/491

**Closed as not planned by grote** 2024-03-14 13:44 UTC
Labels: duplicate
