### ISSUE TITLE
Backup fails: Error -1003 from com.qualcomm.qcrilmsgtunnel fails entire backup

### ISSUE THREAD

**Issue by AlexLJordan** [stevesoltys/backup#625] opened 2024-02-14 11:24 UTC
Hello!
All Backups fail, manual or automatic. I only have 1 backup folder inside `.SeedVaultAndroidBackup` which contains the presumably broken backup and gets overwritten on the next attempt.

Manual shows "backup failed" after roughly 82% progress.

I'm on LinageOS 20-20230909-microG-instantnoodlep with Seedvault Backup 13-3.3

This morning:
[seedvault-13-3.3-1707903746745.txt](https://github.com/seedvault-app/seedvault/files/14278811/seedvault-13-3.3-1707903746745.txt)

Another attempt after resetting backup provider (still local) and resetting recovery code:
[seedvault-13-3.3-1707909773522.txt](https://github.com/seedvault-app/seedvault/files/14278810/seedvault-13-3.3-1707909773522.txt)

Seems similar to #485 and #530, but I don't know. I just want backups to work, thank you.

EDIT:
https://github.com/jackwilsdon/seedvault-extractor does not work on the backup, failing with this error: 
```
error: failed to decrypt metadata: failed to read decrypted data: cipher: message authentication failed
```

**Comment by grote** [comment] 2024-02-14 12:31
Looks like the problems is this:

``` ruby
02-14 10:41:33.356  1801  1867 W BackupManagerService: agentDisconnected: the backup agent for com.qualcomm.qti.telephonyservice died: cancel current operations
02-14 10:41:33.357  1801 29180 I BackupManagerService: [UserID:0] got agent null
02-14 10:41:33.358  1801 29180 W BackupManagerService: Unable to bind to full agent for com.qualcomm.qcrilmsgtunnel
02-14 10:41:33.358  1801 29181 V LifecycleOperationStorage: [UserID:0] Cancel: token=1b5a4ce5
02-14 10:41:33.358  1801 29181 V LifecycleOperationStorage: [UserID:0] Cancel: token=2c8d0ce6
02-14 10:41:33.358  1801 29181 W PFTBT   : Full backup cancel of com.qualcomm.qcrilmsgtunnel
02-14 10:41:33.359  1180  1180 E qdmetadata: paramType 32 not supported
02-14 10:41:33.359  1801 29181 W ActivityManager: Unbinding backup agent with no active backup
02-14 10:41:33.359  1801 29181 W ActivityManager: Process/uid not found attempting kill of com.qti.phone / 10160

02-14 10:41:34.118  1801 25751 W PFTBT   : Error -2003 backing up com.qualcomm.qcrilmsgtunnel
02-14 10:41:34.119 14646 14660 I BackupCoordinator: Request full backup time. Returned 0
02-14 10:41:34.119  1801 25751 I PFTBT   : Transport suggested backoff=0
02-14 10:41:34.119  1801 25751 W PFTBT   : Backup cancelled. package=com.qualcomm.qcrilmsgtunnel, cancelAll=true
02-14 10:41:34.119  1801 25751 W ActivityManager: Unbinding backup agent with no active backup
02-14 10:41:34.120  1801 25751 I PFTBT   : Unbinding agent in com.qualcomm.qcrilmsgtunnel
02-14 10:41:34.120  1801 25751 W ActivityManager: Unbinding backup agent with no active backup
02-14 10:41:34.120  1801 25751 I PFTBT   : Initiating full-data transport backup of com.qualcomm.qti.poweroffalarm token: 458902757
02-14 10:41:34.120  1801 25751 I PFTBT   : Full backup completed with status: -2003
02-14 10:41:34.121 14646 14660 I NotificationBackupObserver: Completed. Target: com.qualcomm.qcrilmsgtunnel, status: -2003
02-14 10:41:34.121 14646 14660 I NotificationBackupObserver: Showing progress notification for com.qti.phone 171/222
02-14 10:41:34.121 14646 14660 I BackupNotificationManager: 238/288 - 83% - com.qualcomm.qcrilmsgtunnel
02-14 10:41:34.123 14646 14646 W BackupNotificationManager: Needed to clean up notification with ID 1
02-14 10:41:34.123 14646 14646 D ConfigurableBackupTransportService: Service destroyed.
```

So indeed a duplicate of #530 I'd say. Maybe we need to loop in some Lineage people about this? @mikeNG maybe knows what this package is and why its backup is broken?

@AlexLJordan does it also only happen when you manually request a backup?

**Comment by AlexLJordan** [comment] 2024-02-14 16:59
Hi! Thanks for the quick reply.
I had initially set up seedvault about half a year back, and ever since not a single backup worked. _Thus, I'd say it happens on automatic _and_ manual backups._

If it helps, SeedVault reports an automatic backup 3 hours ago (which is after I submitted the issue and left it alone, as far as I'm aware) and the new log doesn't show anything about a `BackupManagerService`:
[seedvault-13-3.3-1707929565098.txt](https://github.com/seedvault-app/seedvault/files/14283945/seedvault-13-3.3-1707929565098.txt)

Hope this can be resolved soon :) Thanks so much!

**Comment by grote** [comment] 2024-02-15 13:35
Looks like that new log has nothing backup related. It covers a 3h time window, probably after the backup stopped.

**Comment by grote** [comment] 2024-02-22 16:56
@mikeNG this keeps happening (see #530 also). What are these apps? Is there nothing one can do to fix their backup agents?

**Comment by chirayudesai** [comment] 2024-02-22 17:02
`com.qualcomm.qcrilmsgtunnel` is a proprietary Qualcomm APK and thus it's not exactly trivial / easy to fix.

We should try to handle it better, because it could happen with any app in theory.

**Comment by grote** [comment] 2024-02-22 18:09
Not easy for us to do this though, see https://github.com/seedvault-app/seedvault/issues/491 (we have lots of tickets related to this)

**Comment by chirayudesai** [comment] 2024-02-22 18:33
> Not easy for us to do this though, see #491 (we have lots of tickets related to this)

Ok, then in that case I think it'd be fine to have an OS patch for this

1) Either fix it in frameworks code, which'd help with any / all apps. We can link the patch here.
2) Figure out a way to fix these proprietary apps and fix any - for this one, we could probably disable backup too. It's only going to be present on certain Qualcomm devices, although other devices may have other proprietary apps which lead to issues.

**Comment by fabolhak** [comment] 2024-03-12 15:11
Have the same problem with Sony Xperia 1 III and Lineage OS 20. Tried to disable all "System Apps", but that did not help. It always complains about some `com.qualcomm.*` app.

Is there any workaround for this or can I help someone (e.g. by providing logs, testing, ...)?

**Comment by grote** [comment] 2024-03-14 13:44
Closing as duplicate of https://github.com/seedvault-app/seedvault/issues/491

**Closed as completed by grote** 2024-03-14 13:44 UTC
Labels: duplicate
